version: "3"
   
services:
  api:
    build: .
    platform: linux/amd64
    image: wjddn/recboj:latest
    ports:
      - 8000:8000
    working_dir: /app
    networks:
      - my-custom-network
    environment:
      DATABASE_HOST: postgres-server  # 이 줄을 추가합니다.

networks:
  my-custom-network:
    external: true